### ISSUE TITLE
Missing REST API documentation

### ISSUE THREAD

**Issue by lukehoban** [pulumi/console-requests#394]
Ideally we address https://github.com/pulumi/pulumi-cloud-requests/issues/100 imminently and deliver a "full" OpenAPI spec for the Pulumi Cloud REST API.  

But in the meantime - using this issue to catalogue APIs that exist but are undocumented:
- [x] Policies
  - [x] `/orgs/{orgName}/policygroups` (GET)
  - [x] `/orgs/{orgName}/policygroups/{policyGroup}` (GET)
  - [x] `/orgs/{orgName}/policypacks` (GET)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}/latest` (GET)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}` (GET)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}/schema` (GET)
  - [x] `/orgs/{orgName}/policygroups` (POST)
  - [x] `/orgs/{orgName}/policygroups/{policyGroup}` (PATCH, DELETE)
  - [x] `/orgs/{orgName}/policypacks` (POST)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}` (DELETE)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}/latest` (POST)
  - [x] `/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}` (DELETE)
  - A few more...
- [x] Stacks
  - [x] Create Stack
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/downstreamreferences` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/metadata` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/resources/count` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/resources/latest` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/resources/{version}` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/policygroups` (GET)
  - [x] `/stacks/{orgName}/{projectName}/{stackName}/policypacks` (GET)
- [x] Encryption/decryption
- [x] New Project Wizard Templates and Template Sources
- [x] Agent Pools
- [x] Org Tokens
- [x] Team Tokens
  - [x] `/api/orgs/{orgName}/teams/{team}/tokens` (POST)
- [x] OIDC
  - [x] OIDC Issuers
  - [x] `/oauth/token` (POST)
- More...
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-cloud-requests/issues/427
- [ ] https://github.com/pulumi/pulumi-cloud-requests/issues/428
- [ ] https://github.com/pulumi/pulumi-cloud-requests/issues/429
- [ ] https://github.com/pulumi/pulumi-cloud-requests/issues/430
```

**Comment by meagancojocar** [comment]
Tacking on to this:
- Combine Deployment REST API with Cloud REST API docs.

**Comment by komalali** [comment]
CreateStack API is also undocumented

**Comment by meagancojocar** [comment]
Isn't Delete Stack which we use for TTL also undocumented

**Comment by komalali** [comment]
> Isn't Delete Stack which we use for TTL also undocumented

That's the `deleteAfterDestroy` option in the deployment settings. But yes.

**Comment by meagancojocar** [comment]
I thought that the API endpoint we used for `deleteAfterDestroy` was yet o be documented and it was something that even non-deployments customers could use.

**Comment by ringods** [comment]
Customer wants to create team tokens via the REST api. Via reverse engineering, they found this endpoint:

`/api/orgs/{orgName}/teams/{team}/tokens`

They would like to have this in the official public API too.
